### ISSUE TITLE
Request diff as map[string]interface{}

### ISSUE THREAD

**Issue by rodaine** [d4l3k/messagediff#1]
This is awesome! It would be interesting to get the diff as a `map[string]interface{}` to be able to operate on those differences beyond the string output. Thoughts?

**Comment by parkr** [comment]
:+1: Would love to see this. It seems like the information is there (in the string) – it'd be cool to have something like 

```go
map[string]map[string]interface{}{
    "added": {
        ".A[3]": 2,
    },
    "deleted": {
        ".A[3]": 3,
    },
}
```

**Comment by d4l3k** [comment]
Yeah, that seems completely reasonable. I've been intending to do something similar since the beginning (hence why it's called PrettyDiff instead of just Diff).

Though, while having the path as a string is easiest from an implementation standpoint. It doesn't seem like a particularly clean way of representing the structured data.

It might be best to represent the data as nodes:
```go
type Path []Node
func (p Path) String() string {}

type Node interface {
   String()
}

type StructField string
type MapKey interface{}
type SliceIndex int
```

What are your thoughts?

**Comment by parkr** [comment]
@d4l3k Can you expound on the limitations of my approach? I'm interested in an example as to why the Node approach is preferred. Thanks!

**Comment by d4l3k** [comment]
Here's the main diff struct:
```go
type Diff struct {
    Added, Deleted, Modified map[*Path]interface{}
}
```

Doing it this way allows for much more flexibility when using the data. You can get the same string output by calling .String() on the key of each of the maps as well as the ability to do performant operations such as patching.

When the path is stored as a string, doing things like patching will require writing a parser for the path and an additional layer of complexity.

**Comment by d4l3k** [comment]
I've merged in the DeepDiff function so I'll close this unless there are any significant concerns.

**Comment by rodaine** [comment]
:+1: so fast!
