### ISSUE TITLE
tests fail with go 1.9

### ISSUE THREAD

**Issue by decathorpe** [d4l3k/messagediff#13]
When running "go test" with go 1.9, the following failure occurs:

```
go test -compiler gc -ldflags '' github.com/d4l3k/messagediff
--- FAIL: TestPrettyDiff (0.00s)
	messagediff_test.go:41: 12. PrettyDiff(time.Time{wall:0x0, ext:62135596800, loc:(*time.Location)(nil)}, time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}) diff = "modified: .ext = 0\n"; not "modified: .sec = 0\n"
FAIL
FAIL	github.com/d4l3k/messagediff	0.002s
```

**Comment by d4l3k** [comment]
Hey, are you testing using master or the v1.1.0 tag? The test should be fixed in master. Didn't want to roll a new release just for a test fix.

**Comment by decathorpe** [comment]
Damn, thanks for pointing that out - I was still using an old commit. It works fine with current master.
Sorry for the noise.
