### ISSUE TITLE
testdiff: ignore doesn't work

### ISSUE THREAD

**Issue by BrunoLerner** [d4l3k/messagediff#17]
Hello,

I've copied exactly the example exposed in README and ran it. The output I get is that they are different in the field I told it to ignore.
I am using golang 1.10

Thanks,

**Comment by BrunoLerner** [comment]
turns out its just a problem in the import, it imports the old code

**Comment by d4l3k** [comment]
Yeah, sorry about that, just pushed a new release with the latest code.
