### ISSUE TITLE
Please tag and version this repository

### ISSUE THREAD

**Issue by aviau** [d4l3k/messagediff#4]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for messagediff and versioning would help Debian keep up with development.

**Comment by d4l3k** [comment]
I just added a v1.0.0 tag. Should let you now use `gopkg.in/d4l3k/messagediff.v1`.

I'm glad to hear that you're using it! What are you using it for?

**Comment by aviau** [comment]
messagediff is a dependency for Syncthing!
